// TypeScript types for the description files and the dictionary, generated from the json
// schemas `ddd schema all` writes, so that a change of the file formats the page has not caught
// up with fails the type check instead of reaching a user. Needs the package installed
// (`pip install -e .` at the root of the checkout); DDD names another `ddd` executable.
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { compileFromFile } from "json-schema-to-typescript";

const schemas = mkdtempSync(join(tmpdir(), "ddd-schemas-"));
try {
  const ddd = process.env.DDD ?? "ddd";
  const result = spawnSync(ddd, ["schema", "all", "-o", schemas], { stdio: "inherit" });
  if (result.error !== undefined || result.status !== 0) {
    console.error(`'${ddd} schema all' failed: install the package first (pip install -e .)`);
    process.exit(1);
  }
  const target = new URL("../src/generated/", import.meta.url);
  mkdirSync(target, { recursive: true });
  for (const name of readdirSync(schemas).sort()) {
    const kind = name.replace(/^ddd_/, "").replace(/\.schema\.json$/, "");
    const source = await compileFromFile(join(schemas, name), {
      bannerComment: "/* Generated by scripts/schemas.mjs from `ddd schema all`. Do not edit. */",
      additionalProperties: false,
      style: { printWidth: 100 },
    });
    writeFileSync(new URL(`${kind}.ts`, target), source);
  }
} finally {
  rmSync(schemas, { recursive: true, force: true });
}
