// TypeScript types for the description files and the dictionary, generated from the json
// schemas `ddd schema all` writes, so that a change of the file formats the page has not caught
// up with fails the type check instead of reaching a user. Needs the package installed
// (`pip install -e .` at the root of the checkout); DDD names another `ddd` executable.
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { compile, compileFromFile } from "json-schema-to-typescript";

const schemas = mkdtempSync(join(tmpdir(), "ddd-schemas-"));
try {
  const ddd = process.env.DDD ?? "ddd";
  const result = spawnSync(ddd, ["schema", "all", "-o", schemas], { stdio: "inherit" });
  if (result.error !== undefined || result.status !== 0) {
    console.error(`'${ddd} schema all' failed: install the package first (pip install -e .)`);
    process.exit(1);
  }
  const target = new URL("../src/generated/", import.meta.url);
  mkdirSync(target, { recursive: true });
  for (const name of readdirSync(schemas).sort()) {
    const kind = name.replace(/^ddd_/, "").replace(/\.schema\.json$/, "");
    const source = await compileFromFile(join(schemas, name), {
      bannerComment: "/* Generated by scripts/schemas.mjs from `ddd schema all`. Do not edit. */",
      additionalProperties: false,
      style: { printWidth: 100 },
    });
    writeFileSync(new URL(`${kind}.ts`, target), source);
  }
} finally {
  rmSync(schemas, { recursive: true, force: true });
}

// The api contract: one pydantic model per request and response of src/ddd/gui/api.py, turned
// into one json schema by ddd.gui.contract.api_schema() from the very models api.py validates
// requests against and serves responses as, so a model added there without a page type here
// fails a test of contract.py itself rather than leaving the frontend silently behind what the
// server actually sends. The interpreter rather than the `ddd` launcher, and a short -c snippet
// rather than a command of its own: this is not a file format `ddd schema` publishes, only this
// script's business.
{
  const python = process.env.DDD_PYTHON ?? "python";
  const snippet =
    "import json; from ddd.gui.contract import api_schema; print(json.dumps(api_schema()))";
  const printed = spawnSync(python, ["-c", snippet], { encoding: "utf-8" });
  if (printed.error !== undefined || printed.status !== 0) {
    console.error(`'${python} -c ...' failed: install the package first (pip install -e .)`);
    console.error(printed.stderr);
    process.exit(1);
  }
  const { title: _unused, ...apiSchema } = JSON.parse(printed.stdout);
  // The document has no shape of its own - every request and response is a sibling under
  // $defs, named by the api's own vocabulary - so compile() is given a name for the root it
  // still insists on producing, and the interface that name would print (an untyped index
  // signature nothing in the page ever imports) is dropped below.
  const root = "ApiSchemaRoot";
  const compiled = await compile(apiSchema, root, {
    bannerComment:
      "/* Generated by scripts/schemas.mjs from ddd.gui.contract.api_schema. Do not edit. */",
    additionalProperties: false,
    unreachableDefinitions: true,
    style: { printWidth: 100 },
  });
  const withoutRoot = compiled.replace(
    new RegExp(
      `\\n?/\\*\\*(?:(?!\\*/)[\\s\\S])*\\*/\\nexport interface ${root} \\{(?:(?!\\n\\})[\\s\\S])*\\n\\}\\n`,
    ),
    "\n",
  );
  if (withoutRoot === compiled) {
    throw new Error(`expected a synthetic '${root}' interface to strip from the api schema`);
  }
  writeFileSync(new URL("api.ts", new URL("../src/generated/", import.meta.url)), withoutRoot);
}
