// The JSON the server answers with (src/ddd/gui/api.py), shape for shape - re-exported from
// gui/src/generated/api.ts, generated from src/ddd/gui/contract.py by scripts/schemas.mjs, so
// that a model added to the contract without a page type here fails the build instead of the
// two silently drifting apart.
export type {
  Change,
  Changes,
  EditReply,
  FileContent,
  Finding,
  FindingRoute,
  FixOffered,
  FixReply,
  Found,
  FoundProject,
  GraphDisagreement,
  GraphFlow,
  GraphModule,
  GraphReply,
  Hunk,
  Note,
  Operation,
  PlannedChange,
  PlannedOperation,
  PlanReply,
  ProjectUnit,
  SessionInfo,
  SettleReply,
  Severity,
  SourceFile,
  State,
  UnitEntry,
  UnitPlace,
  UnitReply,
  UnitsReply,
  UsedUnit,
  VariableDeclaration,
  VariableKeyCarried,
  VariableKeyOffer,
  VariableKeyValue,
  VariableReply,
  VocabularyUnit,
} from "../generated/api";
