/* SensorHub.h is generated by DDD out of sensor_hub.ddd.json; it declares exactly what this component declared. */
#include "SensorHub.h"

void sensor_hub_step(void);

void sensor_hub_step(void)
{
    ValueA = 100U;      /* output, writable here */
    ValueB[0] = 3300U;  /* output array */
    ValueC = 21.5F;     /* output */
    FlagA = true;       /* output */
    ValueD[0] = 42U;    /* component local, invisible to every other component */
}
